health/config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
	resources :ratings, shallow: true
	resources :images, shallow: true
  end

  devise_for :users

  root 'recipes#index'

end

health/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :recipe

  validates :filename, presence: true
  validates :recipe_id, presence: true

end

health/app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :recipe

  validates :comment, presence: true
  validates :rate, presence: true

end

health/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ratings
  has_many :images

  validates :recipe_name, presence: true
  validates :ingredients, presence: true

  def generate_filename
	self.image.filename = rand(100000000)
  end

end

health/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

health/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#  before_filter :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :name, :password)}
	end
end

health/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
	recipe = Recipe.find(params[:recipe_id])
    @image = recipe.images.new(image_params)
	#recipe.generate_filename
	@image.filename = rand(1000000000)
	@uploaded_io = params[:image][:uploaded_file]

	File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
		file.write(@uploaded_io.read)
	end

	if @image.save
		redirect_to @image.recipe, notice: 'Image was  successfully created.'
	else
		render :new
	end

#    respond_to do |format|
 #     if @image.save
 #       format.html { redirect_to @recipe, notice: 'Image was successfully created.' }
 #       format.json { render :show, status: :created, location: @image }
 #     else
 #       format.html { render :new }
 #       format.json { render json: @image.errors, status: :unprocessable_entity }
 #     end
 #   end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @recipe, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
	  redirect_to @image.recipe, notice: 'Image was successfully destroyed.'
#    respond_to do |format|
 #     format.html { redirect_to recipes_url, notice: 'Image was successfully destroyed.' }
 #     format.json { head :no_content }
 #   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :recipe_id, :recipe_name)
    end
end

health/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
	recipe = Recipe.find(params[:recipe_id])
    @rating = recipe.ratings.new(rating_params)

	if @rating.save
		redirect_to @rating.recipe, notice: 'Rating was successfully created.'
	else
		render :new
	end
	

#    respond_to do |format|
#      if @rating.save
 #       format.html { redirect_to @rating.recipe, notice: 'Rating was successfully created.' }
  #      format.json { render :show, status: :created, location: @rating }
   #   else
    #    format.html { render :new }
     #   format.json { render json: @rating.errors, status: :unprocessable_entity }
 #     end
 #   end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to recipe_url(@rating.recipe), notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
		redirect_to @rating.recipe, notice: 'Rating was successfully destroyed.'
#    respond_to do |format|
 #     format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
 #     format.json { head :no_content }
 #   end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:recipe_id, :rate, :comment)
    end
end

health/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
	@rating = @recipe.ratings.all
	@rating_new = Rating.new
	@image = @recipe.images.all
	@image_new = Image.new
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @rating = Rating.new
	@image = Image.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create

	@recipe = Recipe.new(recipe_params)

        respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:ingredients, :image, :recipe_name)
    end
end

health/app/helpers/application_helper.rb
module ApplicationHelper
end

health/app/helpers/images_helper.rb
module ImagesHelper
end

health/app/helpers/ratings_helper.rb
module RatingsHelper
end

health/app/helpers/recipes_helper.rb
module RecipesHelper
end

health/app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :recipe_id %><br>
    <%= f.text_field :recipe_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

health/app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

health/app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.filename %></td>
        <td><%= image.recipe %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Wanna Add Another New Image', new_image_path %>

health/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

health/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @image.filename %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @image.recipe %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

health/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="user_nav">
    <% if user_signed_in? %>
	<center>
     Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
	</center>
  </div>


  <title>Health</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

health/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
	<%= f.label :recipe_name %><br>
	<%= f.text_field :recipe_name %><br>
  </div>

  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.text_area :ingredients %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

health/app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

health/app/views/recipes/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

body {
	background-image: url("http://previews.123rf.com/images/romastudio/romastudio1408/romastudio140800009/30548429-Healthy-food-background-studio-photography-of-different-fruits-and-vegetables-on-wooden-table-Stock-Photo.jpg");
}
#floating-box {
	padding: 1px;
	border: 5px solid black;
}
#header {
    background-color:black;
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:300px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    width:350px;
    float:left;
    padding:10px;
}
#footer {
    background-color:black;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;
}
</style>
</head>
<body>

<center style="font-size:250%; font-family:Times;">
<div id="floating-box">
<div id="header">
<h1>The Healthy Choice</h1>
</div>
<h3>Recipe(s) Name</h3>
<% if user_signed_in? %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
		<td><%= recipe.recipe_name %></td>
        <td><%= link_to 'Show', recipe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="footer">
  <%= link_to 'Back', recipes_path %>
  <%= link_to 'New Recipe', new_recipe_path %>
</div>

<% else %>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
		<td><%= recipe.recipe_name %></td>
        <td><%= link_to 'Show', recipe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id="footer"
<%= link_to 'Back', recipes_path %>
</div>

<% end %>
</div>
</center>
</body>
</html>

health/app/views/recipes/new.html.erb
<body style="background-color:lightgrey;font-family:Times">

<!DOCTYPE html>
<html>
<head>
<style>

#floating-box {
	padding: 1px;
	border: 5px solid black;
}

#header {
    background-color:black;
    color:white;
    text-align:center;
    padding:5px;
}

#footer {
    background-color:black;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;
}
</style>
</head>

<center>
<div id="floating-box">
<div id="header">
<h1>New Recipe</h1>
</div>

<%= render 'form' %>

<div id="footer">
<%= link_to 'Back', recipes_path %>
</div>

</div>
</center>
</html>

health/app/views/recipes/show.html.erb
<body style="background-color:lightgrey;font-family:Times">
<!DOCTYPE html>
<html>
<head>
<style>

#border {
	padding: 1px;
	border: 5px solid black;
}

#floating-box {
    display: inline-block;
    border-radius: 25px;
    background: yellow;
    padding: 10px;
	border: 5px solid black;
}

#floating-box2 {
    display: inline-block;
    border-radius: 25px;
    background: lightgreen;
    padding: 10px;
	border: 5px solid black;
}

#header {
    background-color:black;
    color:white;
    text-align:center;
    padding:5px;
}
#nav {
    line-height:30px;
    background-color:#eeeeee;
    height:300px;
    width:100px;
    float:left;
    padding:5px;
}
#section {
    width:350px;
    float:left;
    padding:10px;
}
#footer {
    background-color:black;
    color:white;
    clear:both;
    text-align:center;
    padding:5px;
}
</style>
</head>


<%= link_to 'Back', recipes_path %>

<div id="border">
<% if user_signed_in? %>
<div id="header">
<h1><%= @recipe.recipe_name %></h1>
</div>

<p>
  <% @image.each do |img| %>
   <div id="floating-box">
   <table>
	<% if img.present? %>
		<% if img.recipe_id == @recipe.id %>
		  <td><%= image_tag img.filename, size: "400x250", alt: img.filename %><br>
		  <%= link_to 'Delete Image', img, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
	<% end %>
   </table>
   </div>
  <% end %>
    <br>
</p>

<p>
<div id="floating-box2">
  <strong style="font-size:110%;">Ingredients and Recipe:</strong><br>
  <%= safe_join(@recipe.ingredients.split("\r\n"), "<br/>".html_safe) %>
  <%= link_to 'Edit', edit_recipe_path(@recipe) %>
</div>
</p>

<% if @rating.present? %>
  <div id="border">
    <strong style="font-size:110%;">Listing Ratings</strong>

	<table>
	  <thead>
		<tr>
		  <th>Rate</th>
		  <th>Comment</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>

  <tbody>
    <% @rating.each do |rating| %>
	 <% if rating.present? %>

	   <% if rating.recipe_id == @recipe.id %>
		 <tr>
	      <td><%= rating.rate %></td>
		  <td><%= rating.comment %></td>
		  <td><%= link_to 'Delete', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td><br>
		 </tr>
	   <% end %>
	 <% end %>
    <% end %>
  </tbody>
</table>
</div>
<% end %>


 <p>
  <strong style="font-size:110%;font-family:Times;">Give a Rating</strong>
	<%= form_for([@recipe,@rating_new]) do |new_rat| %>
	  <%= new_rat.label :rate %><br>
	  <%= new_rat.number_field :rate %><br>
	  <%= new_rat.label :comment %><br>
	  <%= new_rat.text_area :comment %><br>
	  <%= new_rat.submit "Add Rating/Comment" %>
	<% end %><br>
 </p>

 <p>
  <strong style="font-size:110%;font-family:Times;">Upload New Image</strong>
	<%= form_for([@recipe,@image_new]) do |new_img| %>
	  <%= new_img.file_field :uploaded_file %><br>
	  <%= new_img.submit 'Add Image' %>
	<% end %><br>
 </p>

<% else %>

<div id="header">
<h1><%= @recipe.recipe_name %></h1>
</div>

<p>
  <% @image.each do |img| %>
   <div id="floating-box">
   <table>
	<% if img.present? %>
		<% if img.recipe_id == @recipe.id %>
		  <td><%= image_tag img.filename, size: "400x250", alt: img.filename %>
		<% end %>
	<% end %>
   </table>
   </div>
  <% end %>
    <br>
</p>

<p>
  <div id="floating-box2">
  <h3>Ingredients:</h3>
  <%= safe_join(@recipe.ingredients.split("\r\n"), "<br/>".html_safe) %>
  </div>
</p>
<br><br>

  <% if @rating.present? %>
	<div id="border">
	<strong style="font-size:110%;font-family:Times;">Listing Ratings</strong>
	<table>
	  <thead>
		<tr>
		  <th>Rate</th>
		  <th>Comment</th>
		  <th colspan="3"></th>
		</tr>
	  </thead>
  <% end %>

  <tbody>
    <% @rating.each do |rating| %>
	 <% if rating.present? %>

	   <% if rating.recipe_id == @recipe.id %>
		 <tr>
	      <td><%= rating.rate %></td>
		  <td><%= rating.comment %></td>
		 </tr>
	   <% end %>
	 <% end %>
    <% end %>
  </tbody>
</table>
</div>
<% end %>

</div>
<div id="footer">
<%= link_to 'Back', recipes_path %>
</html>