img/config/routes.rb
Rails.application.routes.draw do
  resources :images do
    resources :tags, :shallow => true
    resources :image_users, :shallow => true
  end
  devise_for :users
  
  root 'images#index'
  

end

img/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :tags
  has_many :users
  
  def generate_filename
	self.filename = rand(100000000)
  end
end

img/app/models/image_user.rb
class ImageUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
  has_many :images
end

img/app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :image
end

img/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#  before_filter :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :name, :password)}
	end
end

img/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

img/app/controllers/image_users_controller.rb
class ImageUsersController < ApplicationController
  before_action :set_image_user, only: [:show, :edit, :update, :destroy]

  # GET /image_users
  # GET /image_users.json
  def index
    @image_users = ImageUser.all
  end

  # GET /image_users/1
  # GET /image_users/1.json
  def show
  end

  # GET /image_users/new
  def new
	@image = Image.find params[:image_id]
	@image_user = image.image_users.new
	@imgeUser = getUser
  end

  def getUser
	@imgUsers = User.all
	ary = Array.new
	@imgUsers.each do |img|
		ary.push([img.name + '(' + img.email + ') ', img.id])
	end
  	return ary
  end

  # GET /image_users/1/edit
  def edit
	@imgeUser = getUser
  end

  # POST /image_users
  # POST /image_users.json
  def create
    @image_user = ImageUser.new(image_user_params)

    respond_to do |format|
      if @image_user.save
        format.html { redirect_to @image_user, notice: 'Image user was successfully created.' }
        format.json { render :show, status: :created, location: @image_user }
      else
        format.html { render :new }
        format.json { render json: @image_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_users/1
  # PATCH/PUT /image_users/1.json
  def update
    respond_to do |format|
      if @image_user.update(image_user_params)
        format.html { redirect_to @image_user, notice: 'Image user was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_user }
      else
        format.html { render :edit }
        format.json { render json: @image_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_users/1
  # DELETE /image_users/1.json
  def destroy
    @image_user.destroy
    respond_to do |format|
      format.html { redirect_to image_users_url, notice: 'Image user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_user
      @image_user = ImageUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_user_params
      params.require(:image_user).permit(:user_id, :image_id)
    end
end

img/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
	@tag = @image.tags.all
	@tag_new = Tag.new
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

# POST /images
# POST /images
  def create
    @image = Image.new(image_params)
    @image.generate_filename  # a function you write to generate a random filename and put it in the images "filename" variable
    @image.user = current_user

    @uploaded_io = params[:image][:uploaded_file]

    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
        file.write(@uploaded_io.read)
    end

    if @image.save
      redirect_to @image, notice: 'Image was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :private, :user_id)
    end
end

img/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
	image = Image.find(params[:image_id])
    @tag = image.tags.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag.image, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag.image, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to @tag.image, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:image_id, :str)
    end
end

img/app/helpers/home_helper.rb
module HomeHelper
end

img/app/helpers/image_users_helper.rb
module ImageUsersHelper
end

img/app/helpers/tags_helper.rb
module TagsHelper
end

img/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="body">
<body>
<head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="user_nav">
    <% if user_signed_in? %>
     Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>



  <title>Img</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>
</html>

img/app/views/tags/_form.html.erb
<html class="body">
<div class="body">
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :str %><br>
    <%= f.text_field :str %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 </div>
</html>

img/app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', image_path(@tag.image) %>

img/app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Str</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.image %></td>
        <td><%= tag.str %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

img/app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

img/app/views/tags/show.html.erb
<html class="body">
<div class="body">

<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @tag.image %>
</p>

<p>
  <strong>Str:</strong>
  <%= @tag.str %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

</div>
</html>