wbib/config/routes.rb
Rails.application.routes.draw do

  # reference's routes will be nested inside a topic for index, new, and create
  # reference route: 
  #      /topics/:topic_id/references
  #      /topics/:topic_id/references/new
  #      /topics/:topic_id/references/create

  # reference's routes will NOT be nested for show, edit, update, destroy
  # /references/:id/
  resources :topics do
    resources :references, shallow: true
  end

  root 'topics#index'

end

wbib/app/models/reference.rb
class Reference < ActiveRecord::Base

def addhttp
	if not self.url.include?("http://")
		self.url = 'http://' + self.url
	end
end

  before_validation :addhttp

  validates :url, presence: true

  belongs_to :topics

end

wbib/app/models/topic.rb
class Topic < ActiveRecord::Base
    has_many :references, dependent: :destroy
    accepts_nested_attributes_for :references
    def topic
        title + ' ' + description
    end


end

wbib/app/controllers/references_controller.rb
# This controller does not have a show function
# since references are shown by topic, it does not make sense to
# show a single reference

class ReferencesController < ApplicationController
  before_action :set_reference, only: [:edit, :update, :destroy]

  # GET /topics/:topic_id/references
  def index
    # index is now all the references for a single topic (not all the references)
    # the URL will contain the id of the current topic (:topic_id)
    # use the :topic_id parameter to find all the references
    @topic = Topic.find params[:topic_id]
    # the has_many function called in app/models/topic.rb created the 
    # function "references" which will return an array of all the references 
    # with the topic foreign key matching @topic
    @references = @topic.references
  end

  # GET topics/:topic_id/references/new
  # Create a new reference in the context of a Topic object
  # that way the Reference's foreign key (topic_id) will be
  # initialized correctly.
  def new
    # since our the reference new path contains the topic's id
    # we can use params[:topic_id] to get that id
    @topic = Topic.find params[:topic_id]

    # This is similar to Reference.new, BUT it creates the new reference
    # in the context of a Topic object and sets the foreign key
    @reference = @topic.references.new
  end

  # GET /references/1/edit
  def edit
    # edit routes are not nested (we already know our topic's foreign_key)
  end

  # POST topics:/:topic_id/references
  # we need the topic's key in the URL to make sure that someone 
  # isn't trying to hack the id of the new reference's topic
  # rails ensures that the URL has not be tampered with
  def create
    @topic = Topic.find params[:topic_id]
    @reference = @topic.references.new(reference_params)

    if @reference.save
      redirect_to topic_path(@topic) , notice: 'Reference was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /references/1
  # updates don't have to be nested because the topic foreign key is already set
  # and cannot be changed by edit (note that topic_id is not permitted in reference_params())
  def update
    if @reference.update(reference_params)
      redirect_to topic_references_url(@reference.topic), notice: 'Reference was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /references/1
  def destroy
    @reference.destroy
    redirect_to topic_references_url(@reference.topic) , notice: 'Reference was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:url)
    end
end

wbib/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  def show
	@reference = @topic.references.new
  end

  # GET /topics/new
  def new
    @topic = Topic.new

	@reference = @topic.references.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  def create
  # MAGIC SPOT
  # Since the Topic "has_many" ratings, the new function looks
  # for References parameters in the given parameters.  If it finds 
  # them it will also create one (or more) new Reference objects
    @topic = Topic.new(topic_params)

    if @topic.save
      redirect_to @topic, notice: 'Topic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /topics/1
  def update
    if @topic.update(topic_params)
      redirect_to @topic, notice: 'Topic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /topics/1
  def destroy
    @topic.destroy
    redirect_to topics_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description, reference_ref: [:url])
    end
end

wbib/app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
<% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this Topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>


  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% if @topic.references.last.new_record? %>
    <%= f.fields_for :references do |references_form| %>
      <h1>New Reference</h1>
        <div class="field">
          <%= references_form.label :url %><br>
          <%= references_form.text_field :url %>
        </div>
      </div>
    <% end %>
  <% end %>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

wbib/app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show this Topic', @topic %> |
<%= link_to 'Show all Topics', topics_path %>

wbib/app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_topic_path %>

wbib/app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

wbib/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>


<p>
 <h1> <strong>Title:</strong>
  <%= @topic.title%>'s Reference</h1>
<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Timestamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topic.references.each do |reference| %>
      <% if !reference.new_record? %>
       <tr>
        <td><%= reference.url %></td>
        <td><%= reference.created_at.localtime.strftime("%a %b %e %T %Y") %></td>

        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    <% end %>
  </tbody>
</table>
</p>
<br>
<br>

<h3>Create New Reference</h3>
<%= render 'references/form' %>
<br>
<br>

<% if false %>
<%= link_to "Show References", topic_references_path(@topic) %> |
<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Show all Topics', topics_path %>
<% end %>

<%= link_to "Edit #{@topic.title}'s Profile", edit_topic_path(@topic) %> |
<%= link_to 'Show all Topics', topics_path %>